### ISSUE TITLE
imposible reproducir videos

### ISSUE THREAD

**Issue by dapiam** [pablouser1/plugin.video.filmin#2]
Hola,

No consigo reproducir ningun video usando kodi y el plugin para filmin

- kodi Matrix 19.4.0, compilación 2022-03-05
- raspberry pi 2 (ARM v7)
- LibreElec 10.0.2 kernel linux 5.10.95

Esto aparece en el log

```


2022-10-16 22:27:38.819 T:4482     INFO <general>: initializing python engine.
2022-10-16 22:27:42.050 T:4482     INFO <general>: CPythonInvoker(19, /storage/.kodi/addons/plugin.video.filmin/addon.py): script successfully run
2022-10-16 22:27:43.199 T:4482     INFO <general>: Python interpreter stopped
2022-10-16 22:27:46.935 T:4488     INFO <general>: initializing python engine.
2022-10-16 22:27:53.461 T:4488  WARNING <general>: [script.module.inputstreamhelper] Widevine update check was made on 2022-10-15 17:08
2022-10-16 22:27:53.519 T:4488    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'media_viewing_id'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.filmin/addon.py", line 3, in <module>
                                                       run()
                                                     File "/storage/.kodi/addons/plugin.video.filmin/resources/lib/app.py", line 16, in run
                                                       dispatch()
                                                     File "/storage/.kodi/addons/plugin.video.filmin/resources/lib/routes.py", line 84, in dispatch
                                                       dispatcher.run(mode)
                                                     File "/storage/.kodi/addons/plugin.video.filmin/resources/lib/dispatcher.py", line 30, in run
                                                       self.functions[route](*args)
                                                     File "/storage/.kodi/addons/plugin.video.filmin/resources/lib/routes.py", line 71, in _player
                                                       play.start()
                                                     File "/storage/.kodi/addons/plugin.video.filmin/resources/lib/player/Handler.py", line 85, in start
                                                       stream['media_viewing_id'],
                                                   KeyError: 'media_viewing_id'
                                                   -->End of Python script error report<--
                                                   
2022-10-16 22:27:54.727 T:4488     INFO <general>: Python interpreter stopped
2022-10-16 22:27:54.739 T:537     ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.filmin/?menu=player&id=40471]

```

**Comment by pablouser1** [comment]
Buenas, _creo_ que en la nueva versión 1.5.1 ya está solucinado. He tenido que acabar cambiando el `X-Client-Id` por otro. No creo que sea una solución definitiva, pero por ahora funciona correctamente. Cuando tenga tiempo lo arreglaré correctamente.

Intenta reproducir el contenido otra vez y comprueba si ya funciona.

**Comment by dapiam** [comment]
Hola Pablo,

Gracias por el intento pero sigue sin funcionar con la versión 1.5.1

He detectado varios problemas, por ejemplo ahora no reconoce las credenciales para hacer login. He tenido que instalar una versión antigua, hacer login, y actualizar luego a la 1.5.1.

En la versión 1.5.1, te detallo lo que he podido ver:

1. la carpeta collections no aparece nada, en realidad aparecen los items pero sin titulo ni imagen.
2. Al intentar reproducir cualquier pelicula, aparece el siguiente mensaje
Filmin API Error
`Query: select exists(select .....) as "exists" invaid! `

**Comment by pablouser1** [comment]
¡Gracias por la información! Parece que ese cambio de `X-Client-Id` ha movido muchas cosas... He vuelto a poner el que había antes y _espero_ que ya haya solucinado el error del `media_viewing_id`. En la versión 1.5.2 ya he podido usar correctamente todas las funciones del addon.

**Comment by dapiam** [comment]
Hola,

Gracias por el esfuerzo, probando la 1.5.2 sigo sin poder reproducir ningun video, pero ahora ya aparecen collections y catalog.

Al intentar reproducir el error que aparece es el comentado antes, 

`Query: select exists(select * from "media_viewings" where "media_viewings"."user_id" = ? and "media_viewings"."user_id" is not null and "visible" = ? and "media_id" = ? and "user_profile_id" = ? and "media_viewings"."delete_at"  is null) as "exists" invalid! - Data: [XXXXXXX,1,39820,"0"]`

He cambiado el user_id por XXXXXXX pero es un numero.

Tambien sale otro error en Watching, pero esto entiendo que es porque el valor es 0 y no lo gestiona correctamente.
`Invalid uuid format: 0`

**Comment by pablouser1** [comment]
> [XXXXXXX,1,39820,"0"]

Si estoy leyendo bien los datos, ese "0" debería de ser el id de tu perfil (ojo, _no_ el de tu usuario). Debería de ser un uuid (por ejemplo, algo asi: `550e8400-e29b-41d4-a716-446655440000`) así que hay algo que no está funcionando bien.

¿Cuando iniciaste sesión elegiste el perfil que querías usar? Accede a los ajustes del addon, en la sección de "Cuenta" está la entrada "Id del perfil", si el ID es 0, haz click a "Cambiar perfil" y elige uno. Una vez hecho eso, el ID de perfil debería de ser válido.

**Comment by dapiam** [comment]
Perfecto, era eso. He seleccionado un perfil y ahora ya puedo reproducir los videos.

Muchas gracias.
